# "$schema" = "https://starship.rs/config-schema.json"
format = "[î‚¶](color_bg1)$os$username$hostname[î‚°](bg:color_bg2 fg:color_bg1)$directory[î‚°](fg:color_bg2 bg:color_bg3)$git_branch$git_status[î‚°](fg:color_bg3 bg:color_bg4)$c$cpp$rust$golang$nodejs$php$java$kotlin$haskell$python[î‚°](fg:color_bg4 bg:color_bg5)$docker_context$conda$pixi[î‚°](fg:color_bg5 bg:color_bg6)$time[î‚´ ](fg:color_bg6)$line_break$character"
palette = "gruvbox_dark"

[c]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜ž "

[character]
disabled = false
error_symbol = "[>](bold fg:color_red)"
success_symbol = ">"
vimcmd_replace_one_symbol = "[<](fg:color_purple)"
vimcmd_replace_symbol = "[<](fg:color_purple)"
vimcmd_symbol = "_"
vimcmd_visual_symbol = "[<](fg:color_bg2)"

[conda]
format = "[[ $symbol( $environment) ](fg:#83a598 bg:color_bg5)]($style)"
style = "bg:color_bg5"

[cpp]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜ "

[directory]
format = "[ $path ]($style)"
style = "fg:color_fg0 bg:color_bg2"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
Developer = "ó°²‹ "
Documents = "ó°ˆ™ "
Downloads = "ï€™ "
Music = "ó°š "
Pictures = "ï€¾ "

[docker_context]
format = "[[ $symbol( $context) ](fg:#83a598 bg:color_bg5)]($style)"
style = "bg:color_bg5"
symbol = "ïŒˆ"

[git_branch]
format = "[[ $symbol $branch ](fg:color_fg0 bg:color_bg3)]($style)"
style = "bg:color_bg3"
symbol = "ï˜"

[git_status]
ahead = "â‡¡"
behind = "â‡£"
conflicted = "âœ–"
deleted = "âœ–"
diverged = "â‡•"
format = "[[ $all_status$ahead_behind ](fg:color_fg0 bg:color_bg3)]($style)"
modified = "âœš"
renamed = "Â»"
staged = "â—"
stashed = "ðŸ“¦"
style = "bg:color_bg3"
untracked = "â€¦"
up_to_date = "âœ“"

[golang]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜§"

[haskell]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜Ÿ"

[hostname]
format = "[$hostname ]($style)"
ssh_only = false
style = "bg:color_bg1 fg:color_fg0"

[java]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î‰–"

[kotlin]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜´"

[line_break]
disabled = false

[nodejs]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "îœ˜"

[os]
disabled = false
style = "bg:color_bg1 fg:color_fg0"

[os.symbols]
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœŽ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
EndeavourOS = "ï†—"
Fedora = "ó°£›"
Gentoo = "ó°£¨"
Linux = "ó°Œ½"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Mint = "ó°£­"
Pop = "ïŒª"
Raspbian = "ó°¿"
RedHatEnterprise = "ó±„›"
Redhat = "ó±„›"
SUSE = "ïŒ”"
Ubuntu = "ó°•ˆ"
Windows = "ó°²"

[palettes.gruvbox_dark]
# color_bg3 = "#689d6a"
# color_bg6 = "#3c3836"
# color_bg5 = "#665c54"
# color_bg4 = "#458588"
# color_fg0 = "#fbf1c7"
# color_green = "#98971a"
# color_bg1 = "#d65d0e"
# color_purple = "#b16286"
# color_red = "#cc241d"
# color_bg2 = "#d79921"

color_bg4 = "#d65d0e"
color_yellow = "#d79921"
color_bg1 = "#689d6a"
color_bg2 = "#458588"
color_bg5 = "#665c54"
color_bg6 = "#3c3836"
color_fg0 = "#fbf1c7"
color_green = "#98971a"
color_bg3 = "#b16286"
color_red = "#cc241d"

[php]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜ˆ"

[pixi]
format = "[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg5)]($style)"
style = "bg:color_bg5"

[python]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜†"

[rust]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "îž¨"

[time]
disabled = false
format = "[[ ïº $time ](fg:color_fg0 bg:color_bg6)]($style)"
style = "bg:color_bg6"
time_format = "%R"

[username]
format = "[ $user/]($style)"
show_always = true
style_root = "bg:color_bg1 fg:color_fg0"
style_user = "bg:color_bg1 fg:color_fg0"
