# "$schema" = "https://starship.rs/config-schema.json"
format = "[ ](color_bg1)$username$hostname[î‚°](bg:color_bg2 fg:color_bg1)$directory[î‚°](fg:color_bg2 bg:color_bg3)$git_branch$git_status[î‚°](fg:color_bg3 bg:color_bg4)$c$cpp$rust$golang$nodejs$php$java$kotlin$haskell$python[î‚°](fg:color_bg4 bg:color_bg5)$docker_context$conda$pixi[î‚°](fg:color_bg5 bg:color_bg6)$time[î‚° ](fg:color_bg6)$line_break$character"
palette = "gruvbox_dark"

[c]
format = "[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜ž "

[character]
disabled = false
error_symbol = "[>](bold fg:color_red)"
success_symbol = ">"
vimcmd_replace_one_symbol = "[<](fg:color_purple)"
vimcmd_replace_symbol = "[<](fg:color_purple)"
vimcmd_symbol = "_"
vimcmd_visual_symbol = "[<](fg:color_bg2)"

[conda]
format = "[[ $symbol( $environment) ](fg:#83a598 bg:color_bg5)]($style)"
style = "bg:color_bg5"

[cpp]
format = "[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜ "

[directory]
format = "[ $path ]($style)"
style = "fg:color_fg1 bg:color_bg2"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
Developer = "ó°²‹ "
Documents = "ó°ˆ™ "
Downloads = "ï€™ "
Music = "ó°š "
Pictures = "ï€¾ "

[docker_context]
format = "[[ $symbol( $context) ](fg:#83a598 bg:color_bg5)]($style)"
style = "bg:color_bg5"
symbol = "ïŒˆ"

[git_branch]
format = "[[ $symbol $branch ](fg:color_fg1 bg:color_bg3)]($style)"
style = "bg:color_bg3"
symbol = "ï˜"

[git_status]
ahead = "â‡¡"
behind = "â‡£"
conflicted = "âœ–"
deleted = "âœ–"
diverged = "â‡•"
format = "[[ $all_status$ahead_behind ](fg:color_fg1 bg:color_bg3)]($style)"
modified = "âœš"
renamed = "Â»"
staged = "â—"
stashed = "ðŸ“¦"
style = "bg:color_bg3"
untracked = "â€¦"
up_to_date = "âœ“"

[golang]
format = "[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜§"

[haskell]
format = "[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜Ÿ"

[hostname]
format = "[$hostname ]($style)"
ssh_only = false
style = "bg:color_bg1 fg:color_fg1"

[java]
format = "[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î‰–"

[kotlin]
format = "[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜´"

[line_break]
disabled = false

[nodejs]
format = "[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "îœ˜"

[os]
disabled = false
style = "bg:color_bg1 fg:color_fg1"

[os.symbols]
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœŽ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
EndeavourOS = "ï†—"
Fedora = "ó°£›"
Gentoo = "ó°£¨"
Linux = "ó°Œ½"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Mint = "ó°£­"
Pop = "ïŒª"
Raspbian = "ó°¿"
RedHatEnterprise = "ó±„›"
Redhat = "ó±„›"
SUSE = "ïŒ”"
Ubuntu = "ó°•ˆ"
Windows = "ó°²"

[palettes.gruvbox_dark]
# color_bg3 = "#689d6a"
# color_bg6 = "#3c3836"
# color_bg5 = "#665c54"
# color_bg4 = "#458588"
# color_fg0 = "#fbf1c7"
# color_green = "#98971a"
# color_bg1 = "#d65d0e"
# color_purple = "#b16286"
# color_red = "#cc241d"
# color_bg2 = "#d79921"


 color_bg_diff_red = "#402120"
 color_bg_diff_green = "#34381B"
 color_bg_diff_blue = "#0E363E"
 color_bg_statusline1 = "#32302F"
 color_bg_statusline2 = "#3A3735"
 color_bg_statusline3 = "#504945"
 color_bg_current_word = "#3C3836"
 color_bg_visual_red = "#4C3432"
 color_bg_visual_green = "#3B4439"
 color_bg_visual_blue = "#374141"
 color_bg_visual_yellow = "#4F422E"
 color_bg_visual_purple = "#443840"
 color_fg0 = "#D4BE98"
 color_fg1 = "#DDC7A1"
 color_red = "#EA6962"
 color_green = "#A9B665"
 color_blue = "#7DAEA3"
 color_yellow = "#D8A657"
 color_purple = "#D3869B"
 color_orange = "#E78A4E"
 color_aqua = "#89B482"
 color_bg_red = "#EA6962"
 color_bg_green = "#A9B665"
 color_bg_yellow = "#D8A657"
 color_grey0 = "#7C6F64"
 color_grey1 = "#928374"
 color_grey2 = "#A89984"
 color_bg0 = "#1b1b1b"
 color_bg1 = "#282828"
 color_bg2 = "#32302F"
 color_bg3 = "#32302F"
 color_bg4 = "#45403D"
 color_bg5 = "#45403D"
 color_bg6 = "#5A524C"
[php]
format = "[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜ˆ"

[pixi]
format = "[[ $symbol( $version)( $environment) ](fg:color_fg1 bg:color_bg5)]($style)"
style = "bg:color_bg5"

[python]
format = "[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "î˜†"

[rust]
format = "[[ $symbol( $version) ](fg:color_fg1 bg:color_bg4)]($style)"
style = "bg:color_bg4"
symbol = "îž¨"

[time]
disabled = false
format = "[[ ïº $time ](fg:color_fg1 bg:color_bg6)]($style)"
style = "bg:color_bg6"
time_format = "%R"

[username]
format = "[ $user/]($style)"
show_always = true
style_root = "bg:color_bg1 fg:color_fg1"
style_user = "bg:color_bg1 fg:color_fg1"
